name: Add GitHub issues that are getting discussed to the "in discussion" tab of the "Issues" project
on: [issue_comment]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: ${{GET /repos/akleinau/test/issues/1/comments > 2}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/test/projects/1
        GITHUB_PROJECT_COLUMN_NAME: In discussion
   