name: Add GitHub issues that are getting discussed to the "in discussion" tab of the "Issues" project
on: [issue_comment]
jobs:
  print comment count:
    runs-on: ubuntu-latest
    steps:
    - name: load infos
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/test/projects/1
        GITHUB_PROJECT_COLUMN_NAME: In discussion
      run: curl https://api.github.com/repos/akleinau/test/issues/1/comments.
   

   